# DEPRECATED: This workflow will be removed. Please use the new reusable-* workflows.
name: SAST Scan

on:
  workflow_call:
    inputs:
      working_directory:
        description: "Directory containing the source code"
        required: false
        type: string
        default: "."
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarCloud Quality Gate Check
        uses: SonarSource/sonarcloud-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload Sonar Scanner Output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report-${{ github.sha }}
          path: ${{ inputs.working_directory }}/.scannerwork
