name: Trivy ACR Scan

on:
  workflow_call:
    inputs:
      image_name:
        description: "Name of the Docker image"
        required: true
        type: string
      image_tag:
        description: "Tag to verify (e.g., dev-<sha>)"
        required: true
        type: string
      acr_name:
        description: "Azure Container Registry Name"
        required: true
        type: string
      acr_login_server:
        description: "Azure Container Registry Login Server"
        required: true
        type: string

jobs:
  scan:
    name: Trivy Remote Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Docker Login
        run: |
          TOKEN=$(az acr login --name ${{ inputs.acr_name }} --expose-token --output tsv --query accessToken)
          docker login ${{ inputs.acr_login_server }} --username 00000000-0000-0000-0000-000000000000 --password $TOKEN

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ inputs.acr_login_server }}/${{ inputs.image_name }}:${{ inputs.image_tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
