name: Reusable ArgoCD Sync

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
        description: 'ArgoCD application name to sync'
      argocd_server:
        required: false
        type: string
        description: 'ArgoCD Server address'
    secrets:
      ARGOCD_AUTH_TOKEN:
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ inputs.argocd_server != '' && secrets.ARGOCD_AUTH_TOKEN != '' }}
    steps:
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://${{ inputs.argocd_server }}/download/argocd-linux-amd64
          sudo install -m 555 argocd /usr/local/bin/argocd
          rm argocd

      - name: Sync Application
        run: |
          argocd app sync ${{ inputs.app_name }} --server ${{ inputs.argocd_server }} --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }} --grpc-web
