name: Reusable PR Validation

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: false
        type: string
        default: 'Dockerfile'
        description: 'Path to the Dockerfile'
      context_path:
        required: false
        type: string
        default: '.'
        description: 'Docker build context path'
    secrets:
      SONAR_TOKEN:
        required: false
      SNYK_TOKEN:
        required: false

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        if: env.SONAR_TOKEN != ''
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        if: env.SNYK_TOKEN != ''
        uses: snyk/actions/setup@master
        
      - name: Snyk Test
        if: env.SNYK_TOKEN != ''
        continue-on-error: true
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Build Docker Image for scanning
        run: docker build -t temp-image:latest -f ${{ inputs.dockerfile_path }} ${{ inputs.context_path }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'temp-image:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
